# Generated by Django 5.0.1 on 2024-01-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_busowner_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busowner',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
