# Generated by Django 5.0.1 on 2024-01-23 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_busowner_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busowner',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='busowner',
            name='last_name',
        ),
    ]
