# Generated by Django 5.0.1 on 2024-01-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_first_name_busowner_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busowner',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='busowner',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='busowner',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='busowner',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
