# Generated by Django 5.0.1 on 2024-01-25 20:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_remove_busowner_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busname', models.CharField(max_length=100)),
                ('thumbnail', models.CharField(max_length=100)),
                ('seats', models.IntegerField(default=0)),
                ('busowner', models.ForeignKey(db_column='busowner_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_details', to='users.busowner')),
            ],
        ),
        migrations.CreateModel(
            name='BusDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('busRc', models.CharField(max_length=100)),
                ('owner_ID', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('busowner', models.ForeignKey(db_column='bus_doc_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_doc', to='users.busowner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('bus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_features', to='bus.busdetails')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busnumber', models.CharField(max_length=100)),
                ('busowner', models.ForeignKey(db_column='bus_number', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_number_details', to='users.busowner')),
            ],
        ),
        migrations.AddField(
            model_name='busdetails',
            name='busnumber',
            field=models.ForeignKey(db_column='bus_num_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_number', to='bus.busnumber'),
        ),
        migrations.CreateModel(
            name='BusRoutes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('bus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_destination', to='bus.busdetails')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusPoints',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('starting_point', models.CharField(max_length=100)),
                ('destination_point', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('busId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_point_id', to='bus.busdetails')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_points', to='bus.busroutes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
