# Generated by Django 5.0.1 on 2024-01-18 20:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_busowner_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('busname', models.CharField(max_length=100)),
                ('thumbnail', models.CharField(max_length=100)),
                ('busnumber', models.CharField(max_length=100)),
                ('seats', models.IntegerField(default=0)),
                ('busowner', models.ForeignKey(db_column='busowner_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_details', to='users.busowner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('busRc', models.CharField(max_length=100)),
                ('owner_ID', models.CharField(max_length=100)),
                ('busowner', models.ForeignKey(db_column='bus_doc_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_doc', to='users.busowner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('bus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_features', to='bus.busdetails')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
