# Generated by Django 5.0.1 on 2024-02-13 11:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('driver', 'Driver'), ('staff', 'Staff')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BusDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busname', models.CharField(max_length=100)),
                ('busrc', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('thumbnail', models.CharField(max_length=100)),
                ('ac_nonac', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('food', models.BooleanField(default=False)),
                ('drink', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('busowner', models.ForeignKey(db_column='busowner_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_details', to='users.busowner')),
            ],
        ),
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('start', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('starting_time', models.CharField(max_length=100)),
                ('destination_time', models.CharField(max_length=100)),
                ('bus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_route', to='bus.busdetails')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusPoints',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('stop_name', models.CharField(max_length=100)),
                ('stop_order', models.CharField(max_length=100)),
                ('arrival_time', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_points', to='bus.busroute')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date', models.CharField(max_length=100)),
                ('bus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus', to='bus.busdetails')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route', to='bus.busroute')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusStaffSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_schedule', to='bus.busschedule')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_staff', to='bus.busstaff')),
            ],
        ),
    ]
