# Generated by Django 5.0.1 on 2024-02-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetails',
            name='busrc',
            field=models.ImageField(upload_to='bus_rc'),
        ),
        migrations.AlterField(
            model_name='busdetails',
            name='thumbnail',
            field=models.ImageField(upload_to='bus_thumbnail'),
        ),
    ]
