# Generated by Django 5.0.1 on 2024-02-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_alter_busdetails_busrc_alter_busdetails_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetails',
            name='busrc',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='busdetails',
            name='thumbnail',
            field=models.CharField(max_length=100),
        ),
    ]
