# Generated by Django 5.0.1 on 2024-01-18 20:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_busroutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusPoints',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('starting_point', models.CharField(max_length=100)),
                ('destination_point', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('busId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_point_id', to='bus.busdetails')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_points', to='bus.busroutes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
