# Generated by Django 5.0.1 on 2024-02-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_alter_busdetails_busrc_alter_busdetails_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetails',
            name='busrc',
            field=models.ImageField(upload_to='busrc'),
        ),
        migrations.AlterField(
            model_name='busdetails',
            name='thumbnail',
            field=models.ImageField(upload_to='busthumbnail'),
        ),
    ]
