# Generated by Django 5.0.1 on 2024-02-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_remove_busschedule_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='busschedule',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('In-active', 'In-active')], default='active', max_length=100),
        ),
    ]
