# Generated by Django 5.0.1 on 2024-02-28 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0006_busschedule_status'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstaff',
            name='busowner',
            field=models.ForeignKey(db_column='busowner', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_detail', to='users.busowner'),
        ),
    ]
