# Generated by Django 5.0.1 on 2024-02-13 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bus', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('total', models.PositiveIntegerField()),
                ('payment_status', models.CharField(choices=[('SUCCESS', 'success'), ('FAILURE', 'failure')], max_length=255)),
                ('referral_code_used', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('referred_user', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('buspoint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_point', to='bus.buspoints')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BusReservationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('ticket_number', models.CharField(max_length=100)),
                ('seat_number', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('reservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_reservation', to='reservation.busreservation')),
            ],
        ),
    ]
