# Generated by Django 5.0.1 on 2024-03-01 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0007_busstaff_busowner'),
        ('reservation', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busreservation',
            name='buspoint',
        ),
        migrations.AddField(
            model_name='busreservation',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_reservations', to='bus.busdetails'),
        ),
        migrations.AddField(
            model_name='busreservation',
            name='dropoff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dropoff_reservations', to='bus.buspoints'),
        ),
        migrations.AddField(
            model_name='busreservation',
            name='pickup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_reservations', to='bus.buspoints'),
        ),
        migrations.AlterField(
            model_name='busreservation',
            name='referral_code_used',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='busreservation',
            name='referred_user',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='busreservation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_reservations', to='users.userprofile'),
        ),
    ]
